[project]
name = "simple-token"
description = "A simple token contract for hackathon MVP"
authors = []
telemetry = false
cache_dir = "./.clarinet"

[contracts.simple-token]
path = "contracts/simple-token.clar"
clarity_version = 2
epoch = 2.4

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
